--ALTER session set "_oracle_script"=true;
--CREATE USER PARTITURAS IDENTIFIED BY PARTITURAS;
--GRANT CONNECT, RESOURCE, DBA TO PARTITURAS;

/*NO ACEPTA ESTO EN ORACLE, TAMPOCO ACEPTA BOOLEAN
 * CREATE TYPE TIPO_NOTA AS
ENUM('BLANCA', 'NEGRA');*/ 

CREATE TABLE NOTA(
	NOMBRE VARCHAR2(3),
	TIPO VARCHAR2(10),
	ALTA VARCHAR2(1),
	CONSTRAINT PK_NOTA PRIMARY KEY(NOMBRE, TIPO, ALTA),
	CONSTRAINT CH_NOTA_TIPO CHECK (TIPO IN ('BLANCA', 'NEGRA')),
	CONSTRAINT CH_NOTA_ALTA CHECK (ALTA IN ('0', '1'))--0 FALSE 1 TRUE
);
