ALTER session set "_oracle_script"=true;
CREATE USER PARTITURAS IDENTIFIED BY PARTITURAS;
GRANT CONNECT, RESOURCE, DBA TO PARTITURAS;

CREATE TABLE NOTA(
	NOMBRE VARCHAR2(3),
	ALTA BOOLEAN,
	TIPO ENUM("BLANCA", "NEGRA"),
	CONSTRAINT PK_NOTA PRIMARY KEY(NOMBRE, ALTA, TIPO)
);
